export const jobBoardData = [
  {
    id: "1",
    jobTitle: "Software Engineer",
    companyName: "TechCorp",
    jobPackage: "15 - 20 LPA",
    workType: "Onsite",
    experience: "5 - 7 years",
    location: "Noida, India",
    roleType: "Fulltime",
    skills: ["SQL", "Node.js", "React.js", "Express.js", "Salesforce"],
    applyLink: "https://example.com/apply",
    jobDescription:
      "As a Software Engineer you will be specializing in Java and SQL and play a vital role in designing, developing, and maintaining robust software applications that leverage the strengths of Java for application logic and SQL for database interactions. This role requires a solid understanding of Java programming, including object-oriented design principles as well as writing efficient SQL queries in relational databases or NoSQL. This role also involves debugging and resolving software defects, optimizing code for performance, and maintain code quality.",
    keyResponsibilities: [
      "Analyze, design, develop, test, and maintain scalable applications using Java for backend and modern JavaScript frameworks for frontend",
      "Build distributed system based on service-oriented architecture and SOLID design principles",
      "Develop and optimize SQL queries, and database schema designs",
      "Write clean, maintainable, and efficient code following best practices and coding standards",
      "Be passionate about delivering quality code and build culture of continuous learning and improvement in team by identifying technical debts/improvements",
      "Have the desire to collaborate, and like sharing and learning from your colleagues",
      "Provide input and guidance to resolve issues and meet objectives",
    ],
    requiredSkillsExperienceQualifications: [
      "BE/BTech or MS degree in Computer Science from a reputed university",
      "4+ years of full-stack, hands on experience designing & developing of product development experience in Java and related technologies",
      "Experience implementing Design Patterns/SOLID principles/OOPS",
      "Experience developing and working with databases (Oracle, MSSQL, NoSQL)",
      "Experience in successful implementation/adoption of Agile and Scrum methodologies",
      "Test-driven development, which includes Unit and End-to-End Testing",
      "Excellent analytical, problem-solving and communication skills",
      "Experience working with teams across different time-zones and countries",
      "Ability to work independently and collaboratively",
    ],
    aboutCompany: [
      "We’re a diverse group of visionary innovators who provide trading and workflow automation software, high-value analytics, and strategic consulting to corporations, central banks, financial institutions, and governments. Founded in 1999, we’ve achieved tremendous growth by bringing together some of the best and most successful financial technology companies in the world.",
      "Over 2,000 of the world’s leading corporations, including 50% of the Fortune 500 and 30% of the world’s central banks, trust ION solutions to manage their cash, in-house banking, commodity supply chain, trading and risk.",
      "Over 800 of the world’s leading banks and broker-dealers use our electronic trading platforms to operate the world’s financial market infrastructure.",
    ],
    status: "archieved",
  },
  {
    id: "15",
    jobTitle: "Software Engineer",
    companyName: "TechCorp",
    jobPackage: "15 - 20 LPA",
    workType: "Onsite",
    experience: "5 - 7 years",
    location: "Noida, India",
    roleType: "Fulltime",
    skills: ["SQL", "Node.js", "React.js", "Express.js", "Salesforce"],
    applyLink: "https://example.com/apply",
    jobDescription:
      "As a Software Engineer you will be specializing in Java and SQL and play a vital role in designing, developing, and maintaining robust software applications that leverage the strengths of Java for application logic and SQL for database interactions. This role requires a solid understanding of Java programming, including object-oriented design principles as well as writing efficient SQL queries in relational databases or NoSQL. This role also involves debugging and resolving software defects, optimizing code for performance, and maintain code quality.",
    keyResponsibilities: [
      "Analyze, design, develop, test, and maintain scalable applications using Java for backend and modern JavaScript frameworks for frontend",
      "Build distributed system based on service-oriented architecture and SOLID design principles",
      "Develop and optimize SQL queries, and database schema designs",
      "Write clean, maintainable, and efficient code following best practices and coding standards",
      "Be passionate about delivering quality code and build culture of continuous learning and improvement in team by identifying technical debts/improvements",
      "Have the desire to collaborate, and like sharing and learning from your colleagues",
      "Provide input and guidance to resolve issues and meet objectives",
    ],
    requiredSkillsExperienceQualifications: [
      "BE/BTech or MS degree in Computer Science from a reputed university",
      "4+ years of full-stack, hands on experience designing & developing of product development experience in Java and related technologies",
      "Experience implementing Design Patterns/SOLID principles/OOPS",
      "Experience developing and working with databases (Oracle, MSSQL, NoSQL)",
      "Experience in successful implementation/adoption of Agile and Scrum methodologies",
      "Test-driven development, which includes Unit and End-to-End Testing",
      "Excellent analytical, problem-solving and communication skills",
      "Experience working with teams across different time-zones and countries",
      "Ability to work independently and collaboratively",
    ],
    aboutCompany: [
      "We’re a diverse group of visionary innovators who provide trading and workflow automation software, high-value analytics, and strategic consulting to corporations, central banks, financial institutions, and governments. Founded in 1999, we’ve achieved tremendous growth by bringing together some of the best and most successful financial technology companies in the world.",
      "Over 2,000 of the world’s leading corporations, including 50% of the Fortune 500 and 30% of the world’s central banks, trust ION solutions to manage their cash, in-house banking, commodity supply chain, trading and risk.",
      "Over 800 of the world’s leading banks and broker-dealers use our electronic trading platforms to operate the world’s financial market infrastructure.",
    ],
    status: "archieved",
  },
  {
    id: "16",
    jobTitle: "Software Engineer",
    companyName: "TechCorp",
    jobPackage: "15 - 20 LPA",
    workType: "Onsite",
    experience: "5 - 7 years",
    location: "Noida, India",
    roleType: "Fulltime",
    skills: ["SQL", "Node.js", "React.js", "Express.js", "Salesforce"],
    applyLink: "https://example.com/apply",
    jobDescription:
      "As a Software Engineer you will be specializing in Java and SQL and play a vital role in designing, developing, and maintaining robust software applications that leverage the strengths of Java for application logic and SQL for database interactions. This role requires a solid understanding of Java programming, including object-oriented design principles as well as writing efficient SQL queries in relational databases or NoSQL. This role also involves debugging and resolving software defects, optimizing code for performance, and maintain code quality.",
    keyResponsibilities: [
      "Analyze, design, develop, test, and maintain scalable applications using Java for backend and modern JavaScript frameworks for frontend",
      "Build distributed system based on service-oriented architecture and SOLID design principles",
      "Develop and optimize SQL queries, and database schema designs",
      "Write clean, maintainable, and efficient code following best practices and coding standards",
      "Be passionate about delivering quality code and build culture of continuous learning and improvement in team by identifying technical debts/improvements",
      "Have the desire to collaborate, and like sharing and learning from your colleagues",
      "Provide input and guidance to resolve issues and meet objectives",
    ],
    requiredSkillsExperienceQualifications: [
      "BE/BTech or MS degree in Computer Science from a reputed university",
      "4+ years of full-stack, hands on experience designing & developing of product development experience in Java and related technologies",
      "Experience implementing Design Patterns/SOLID principles/OOPS",
      "Experience developing and working with databases (Oracle, MSSQL, NoSQL)",
      "Experience in successful implementation/adoption of Agile and Scrum methodologies",
      "Test-driven development, which includes Unit and End-to-End Testing",
      "Excellent analytical, problem-solving and communication skills",
      "Experience working with teams across different time-zones and countries",
      "Ability to work independently and collaboratively",
    ],
    aboutCompany: [
      "We’re a diverse group of visionary innovators who provide trading and workflow automation software, high-value analytics, and strategic consulting to corporations, central banks, financial institutions, and governments. Founded in 1999, we’ve achieved tremendous growth by bringing together some of the best and most successful financial technology companies in the world.",
      "Over 2,000 of the world’s leading corporations, including 50% of the Fortune 500 and 30% of the world’s central banks, trust ION solutions to manage their cash, in-house banking, commodity supply chain, trading and risk.",
      "Over 800 of the world’s leading banks and broker-dealers use our electronic trading platforms to operate the world’s financial market infrastructure.",
    ],
    status: "archieved",
  },
  {
    id: "17",
    jobTitle: "Software Engineer",
    companyName: "TechCorp",
    jobPackage: "15 - 20 LPA",
    workType: "Onsite",
    experience: "5 - 7 years",
    location: "Noida, India",
    roleType: "Fulltime",
    skills: ["SQL", "Node.js", "React.js", "Express.js", "Salesforce"],
    applyLink: "https://example.com/apply",
    jobDescription:
      "As a Software Engineer you will be specializing in Java and SQL and play a vital role in designing, developing, and maintaining robust software applications that leverage the strengths of Java for application logic and SQL for database interactions. This role requires a solid understanding of Java programming, including object-oriented design principles as well as writing efficient SQL queries in relational databases or NoSQL. This role also involves debugging and resolving software defects, optimizing code for performance, and maintain code quality.",
    keyResponsibilities: [
      "Analyze, design, develop, test, and maintain scalable applications using Java for backend and modern JavaScript frameworks for frontend",
      "Build distributed system based on service-oriented architecture and SOLID design principles",
      "Develop and optimize SQL queries, and database schema designs",
      "Write clean, maintainable, and efficient code following best practices and coding standards",
      "Be passionate about delivering quality code and build culture of continuous learning and improvement in team by identifying technical debts/improvements",
      "Have the desire to collaborate, and like sharing and learning from your colleagues",
      "Provide input and guidance to resolve issues and meet objectives",
    ],
    requiredSkillsExperienceQualifications: [
      "BE/BTech or MS degree in Computer Science from a reputed university",
      "4+ years of full-stack, hands on experience designing & developing of product development experience in Java and related technologies",
      "Experience implementing Design Patterns/SOLID principles/OOPS",
      "Experience developing and working with databases (Oracle, MSSQL, NoSQL)",
      "Experience in successful implementation/adoption of Agile and Scrum methodologies",
      "Test-driven development, which includes Unit and End-to-End Testing",
      "Excellent analytical, problem-solving and communication skills",
      "Experience working with teams across different time-zones and countries",
      "Ability to work independently and collaboratively",
    ],
    aboutCompany: [
      "We’re a diverse group of visionary innovators who provide trading and workflow automation software, high-value analytics, and strategic consulting to corporations, central banks, financial institutions, and governments. Founded in 1999, we’ve achieved tremendous growth by bringing together some of the best and most successful financial technology companies in the world.",
      "Over 2,000 of the world’s leading corporations, including 50% of the Fortune 500 and 30% of the world’s central banks, trust ION solutions to manage their cash, in-house banking, commodity supply chain, trading and risk.",
      "Over 800 of the world’s leading banks and broker-dealers use our electronic trading platforms to operate the world’s financial market infrastructure.",
    ],
    status: "archieved",
  },
  {
    id: "2",
    jobTitle: "Backend Developer",
    companyName: "Innovatech",
    jobPackage: "12 - 18 LPA",
    workType: "Remote",
    experience: "3 - 5 years",
    location: "Bangalore",
    roleType: "Fulltime",
    skills: ["Java", "Spring Boot", "Microservices", "Docker"],
    applyLink: "https://example.com/apply",
    jobDescription:
      "As a Software Engineer you will be specializing in Java and SQL and play a vital role in designing, developing, and maintaining robust software applications that leverage the strengths of Java for application logic and SQL for database interactions. This role requires a solid understanding of Java programming, including object-oriented design principles as well as writing efficient SQL queries in relational databases or NoSQL. This role also involves debugging and resolving software defects, optimizing code for performance, and maintain code quality.",
    keyResponsibilities: [
      "Analyze, design, develop, test, and maintain scalable applications using Java for backend and modern JavaScript frameworks for frontend",
      "Build distributed system based on service-oriented architecture and SOLID design principles",
      "Develop and optimize SQL queries, and database schema designs",
      "Write clean, maintainable, and efficient code following best practices and coding standards",
      "Be passionate about delivering quality code and build culture of continuous learning and improvement in team by identifying technical debts/improvements",
      "Have the desire to collaborate, and like sharing and learning from your colleagues",
      "Provide input and guidance to resolve issues and meet objectives",
    ],
    requiredSkillsExperienceQualifications: [
      "BE/BTech or MS degree in Computer Science from a reputed university",
      "4+ years of full-stack, hands on experience designing & developing of product development experience in Java and related technologies",
      "Experience implementing Design Patterns/SOLID principles/OOPS",
      "Experience developing and working with databases (Oracle, MSSQL, NoSQL)",
      "Experience in successful implementation/adoption of Agile and Scrum methodologies",
      "Test-driven development, which includes Unit and End-to-End Testing",
      "Excellent analytical, problem-solving and communication skills",
      "Experience working with teams across different time-zones and countries",
      "Ability to work independently and collaboratively",
    ],
    aboutCompany: [
      "We’re a diverse group of visionary innovators who provide trading and workflow automation software, high-value analytics, and strategic consulting to corporations, central banks, financial institutions, and governments. Founded in 1999, we’ve achieved tremendous growth by bringing together some of the best and most successful financial technology companies in the world.",
      "Over 2,000 of the world’s leading corporations, including 50% of the Fortune 500 and 30% of the world’s central banks, trust ION solutions to manage their cash, in-house banking, commodity supply chain, trading and risk.",
      "Over 800 of the world’s leading banks and broker-dealers use our electronic trading platforms to operate the world’s financial market infrastructure.",
    ],
    status: "applied",
  },
  {
    id: "3",
    jobTitle: "Frontend Developer",
    companyName: "WebWorks",
    jobPackage: "10 - 15 LPA",
    workType: "Onsite",
    experience: "2 - 4 years",
    location: "Mumbai",
    roleType: "Contract",
    skills: ["HTML", "CSS", "JavaScript", "React.js"],
    applyLink: "https://example.com/apply",
    jobDescription:
      "As a Software Engineer you will be specializing in Java and SQL and play a vital role in designing, developing, and maintaining robust software applications that leverage the strengths of Java for application logic and SQL for database interactions. This role requires a solid understanding of Java programming, including object-oriented design principles as well as writing efficient SQL queries in relational databases or NoSQL. This role also involves debugging and resolving software defects, optimizing code for performance, and maintain code quality.",
    keyResponsibilities: [
      "Analyze, design, develop, test, and maintain scalable applications using Java for backend and modern JavaScript frameworks for frontend",
      "Build distributed system based on service-oriented architecture and SOLID design principles",
      "Develop and optimize SQL queries, and database schema designs",
      "Write clean, maintainable, and efficient code following best practices and coding standards",
      "Be passionate about delivering quality code and build culture of continuous learning and improvement in team by identifying technical debts/improvements",
      "Have the desire to collaborate, and like sharing and learning from your colleagues",
      "Provide input and guidance to resolve issues and meet objectives",
    ],
    requiredSkillsExperienceQualifications: [
      "BE/BTech or MS degree in Computer Science from a reputed university",
      "4+ years of full-stack, hands on experience designing & developing of product development experience in Java and related technologies",
      "Experience implementing Design Patterns/SOLID principles/OOPS",
      "Experience developing and working with databases (Oracle, MSSQL, NoSQL)",
      "Experience in successful implementation/adoption of Agile and Scrum methodologies",
      "Test-driven development, which includes Unit and End-to-End Testing",
      "Excellent analytical, problem-solving and communication skills",
      "Experience working with teams across different time-zones and countries",
      "Ability to work independently and collaboratively",
    ],
    aboutCompany: [
      "We’re a diverse group of visionary innovators who provide trading and workflow automation software, high-value analytics, and strategic consulting to corporations, central banks, financial institutions, and governments. Founded in 1999, we’ve achieved tremendous growth by bringing together some of the best and most successful financial technology companies in the world.",
      "Over 2,000 of the world’s leading corporations, including 50% of the Fortune 500 and 30% of the world’s central banks, trust ION solutions to manage their cash, in-house banking, commodity supply chain, trading and risk.",
      "Over 800 of the world’s leading banks and broker-dealers use our electronic trading platforms to operate the world’s financial market infrastructure.",
    ],
    status: "offer",
  },
  {
    id: "4",
    jobTitle: "DevOps Engineer",
    companyName: "CloudNet",
    jobPackage: "14 - 19 LPA",
    workType: "Remote",
    experience: "4 - 6 years",
    location: "Hyderabad",
    roleType: "Fulltime",
    skills: ["AWS", "Kubernetes", "Terraform", "CI/CD"],
    applyLink: "https://example.com/apply",
    jobDescription:
      "As a Software Engineer you will be specializing in Java and SQL and play a vital role in designing, developing, and maintaining robust software applications that leverage the strengths of Java for application logic and SQL for database interactions. This role requires a solid understanding of Java programming, including object-oriented design principles as well as writing efficient SQL queries in relational databases or NoSQL. This role also involves debugging and resolving software defects, optimizing code for performance, and maintain code quality.",
    keyResponsibilities: [
      "Analyze, design, develop, test, and maintain scalable applications using Java for backend and modern JavaScript frameworks for frontend",
      "Build distributed system based on service-oriented architecture and SOLID design principles",
      "Develop and optimize SQL queries, and database schema designs",
      "Write clean, maintainable, and efficient code following best practices and coding standards",
      "Be passionate about delivering quality code and build culture of continuous learning and improvement in team by identifying technical debts/improvements",
      "Have the desire to collaborate, and like sharing and learning from your colleagues",
      "Provide input and guidance to resolve issues and meet objectives",
    ],
    requiredSkillsExperienceQualifications: [
      "BE/BTech or MS degree in Computer Science from a reputed university",
      "4+ years of full-stack, hands on experience designing & developing of product development experience in Java and related technologies",
      "Experience implementing Design Patterns/SOLID principles/OOPS",
      "Experience developing and working with databases (Oracle, MSSQL, NoSQL)",
      "Experience in successful implementation/adoption of Agile and Scrum methodologies",
      "Test-driven development, which includes Unit and End-to-End Testing",
      "Excellent analytical, problem-solving and communication skills",
      "Experience working with teams across different time-zones and countries",
      "Ability to work independently and collaboratively",
    ],
    aboutCompany: [
      "We’re a diverse group of visionary innovators who provide trading and workflow automation software, high-value analytics, and strategic consulting to corporations, central banks, financial institutions, and governments. Founded in 1999, we’ve achieved tremendous growth by bringing together some of the best and most successful financial technology companies in the world.",
      "Over 2,000 of the world’s leading corporations, including 50% of the Fortune 500 and 30% of the world’s central banks, trust ION solutions to manage their cash, in-house banking, commodity supply chain, trading and risk.",
      "Over 800 of the world’s leading banks and broker-dealers use our electronic trading platforms to operate the world’s financial market infrastructure.",
    ],
    status: "followUpRequired",
  },
  {
    id: "5",
    jobTitle: "Data Scientist",
    companyName: "DataMinds",
    jobPackage: "16 - 22 LPA",
    workType: "Onsite",
    experience: "5 - 7 years",
    location: "Pune",
    roleType: "Fulltime",
    skills: ["Python", "R", "Machine Learning", "Data Analysis"],
    applyLink: "https://example.com/apply",
    jobDescription:
      "As a Software Engineer you will be specializing in Java and SQL and play a vital role in designing, developing, and maintaining robust software applications that leverage the strengths of Java for application logic and SQL for database interactions. This role requires a solid understanding of Java programming, including object-oriented design principles as well as writing efficient SQL queries in relational databases or NoSQL. This role also involves debugging and resolving software defects, optimizing code for performance, and maintain code quality.",
    keyResponsibilities: [
      "Analyze, design, develop, test, and maintain scalable applications using Java for backend and modern JavaScript frameworks for frontend",
      "Build distributed system based on service-oriented architecture and SOLID design principles",
      "Develop and optimize SQL queries, and database schema designs",
      "Write clean, maintainable, and efficient code following best practices and coding standards",
      "Be passionate about delivering quality code and build culture of continuous learning and improvement in team by identifying technical debts/improvements",
      "Have the desire to collaborate, and like sharing and learning from your colleagues",
      "Provide input and guidance to resolve issues and meet objectives",
    ],
    requiredSkillsExperienceQualifications: [
      "BE/BTech or MS degree in Computer Science from a reputed university",
      "4+ years of full-stack, hands on experience designing & developing of product development experience in Java and related technologies",
      "Experience implementing Design Patterns/SOLID principles/OOPS",
      "Experience developing and working with databases (Oracle, MSSQL, NoSQL)",
      "Experience in successful implementation/adoption of Agile and Scrum methodologies",
      "Test-driven development, which includes Unit and End-to-End Testing",
      "Excellent analytical, problem-solving and communication skills",
      "Experience working with teams across different time-zones and countries",
      "Ability to work independently and collaboratively",
    ],
    aboutCompany: [
      "We’re a diverse group of visionary innovators who provide trading and workflow automation software, high-value analytics, and strategic consulting to corporations, central banks, financial institutions, and governments. Founded in 1999, we’ve achieved tremendous growth by bringing together some of the best and most successful financial technology companies in the world.",
      "Over 2,000 of the world’s leading corporations, including 50% of the Fortune 500 and 30% of the world’s central banks, trust ION solutions to manage their cash, in-house banking, commodity supply chain, trading and risk.",
      "Over 800 of the world’s leading banks and broker-dealers use our electronic trading platforms to operate the world’s financial market infrastructure.",
    ],
    status: "applied",
  },
  {
    id: "6",
    jobTitle: "Mobile App Developer",
    companyName: "Appify",
    jobPackage: "11 - 16 LPA",
    workType: "Remote",
    experience: "3 - 5 years",
    location: "Chennai",
    roleType: "Fulltime",
    skills: ["Kotlin", "Swift", "React Native", "Flutter"],
    applyLink: "https://example.com/apply",
    jobDescription:
      "As a Software Engineer you will be specializing in Java and SQL and play a vital role in designing, developing, and maintaining robust software applications that leverage the strengths of Java for application logic and SQL for database interactions. This role requires a solid understanding of Java programming, including object-oriented design principles as well as writing efficient SQL queries in relational databases or NoSQL. This role also involves debugging and resolving software defects, optimizing code for performance, and maintain code quality.",
    keyResponsibilities: [
      "Analyze, design, develop, test, and maintain scalable applications using Java for backend and modern JavaScript frameworks for frontend",
      "Build distributed system based on service-oriented architecture and SOLID design principles",
      "Develop and optimize SQL queries, and database schema designs",
      "Write clean, maintainable, and efficient code following best practices and coding standards",
      "Be passionate about delivering quality code and build culture of continuous learning and improvement in team by identifying technical debts/improvements",
      "Have the desire to collaborate, and like sharing and learning from your colleagues",
      "Provide input and guidance to resolve issues and meet objectives",
    ],
    requiredSkillsExperienceQualifications: [
      "BE/BTech or MS degree in Computer Science from a reputed university",
      "4+ years of full-stack, hands on experience designing & developing of product development experience in Java and related technologies",
      "Experience implementing Design Patterns/SOLID principles/OOPS",
      "Experience developing and working with databases (Oracle, MSSQL, NoSQL)",
      "Experience in successful implementation/adoption of Agile and Scrum methodologies",
      "Test-driven development, which includes Unit and End-to-End Testing",
      "Excellent analytical, problem-solving and communication skills",
      "Experience working with teams across different time-zones and countries",
      "Ability to work independently and collaboratively",
    ],
    aboutCompany: [
      "We’re a diverse group of visionary innovators who provide trading and workflow automation software, high-value analytics, and strategic consulting to corporations, central banks, financial institutions, and governments. Founded in 1999, we’ve achieved tremendous growth by bringing together some of the best and most successful financial technology companies in the world.",
      "Over 2,000 of the world’s leading corporations, including 50% of the Fortune 500 and 30% of the world’s central banks, trust ION solutions to manage their cash, in-house banking, commodity supply chain, trading and risk.",
      "Over 800 of the world’s leading banks and broker-dealers use our electronic trading platforms to operate the world’s financial market infrastructure.",
    ],
    status: "archieved",
  },
  {
    id: "7",
    jobTitle: "Full Stack Developer",
    companyName: "FullStackers",
    jobPackage: "13 - 18 LPA",
    workType: "Onsite",
    experience: "4 - 6 years",
    location: "Delhi",
    roleType: "Fulltime",
    skills: ["Node.js", "React.js", "MongoDB", "Express.js"],
    applyLink: "https://example.com/apply",
    jobDescription:
      "As a Software Engineer you will be specializing in Java and SQL and play a vital role in designing, developing, and maintaining robust software applications that leverage the strengths of Java for application logic and SQL for database interactions. This role requires a solid understanding of Java programming, including object-oriented design principles as well as writing efficient SQL queries in relational databases or NoSQL. This role also involves debugging and resolving software defects, optimizing code for performance, and maintain code quality.",
    keyResponsibilities: [
      "Analyze, design, develop, test, and maintain scalable applications using Java for backend and modern JavaScript frameworks for frontend",
      "Build distributed system based on service-oriented architecture and SOLID design principles",
      "Develop and optimize SQL queries, and database schema designs",
      "Write clean, maintainable, and efficient code following best practices and coding standards",
      "Be passionate about delivering quality code and build culture of continuous learning and improvement in team by identifying technical debts/improvements",
      "Have the desire to collaborate, and like sharing and learning from your colleagues",
      "Provide input and guidance to resolve issues and meet objectives",
    ],
    requiredSkillsExperienceQualifications: [
      "BE/BTech or MS degree in Computer Science from a reputed university",
      "4+ years of full-stack, hands on experience designing & developing of product development experience in Java and related technologies",
      "Experience implementing Design Patterns/SOLID principles/OOPS",
      "Experience developing and working with databases (Oracle, MSSQL, NoSQL)",
      "Experience in successful implementation/adoption of Agile and Scrum methodologies",
      "Test-driven development, which includes Unit and End-to-End Testing",
      "Excellent analytical, problem-solving and communication skills",
      "Experience working with teams across different time-zones and countries",
      "Ability to work independently and collaboratively",
    ],
    aboutCompany: [
      "We’re a diverse group of visionary innovators who provide trading and workflow automation software, high-value analytics, and strategic consulting to corporations, central banks, financial institutions, and governments. Founded in 1999, we’ve achieved tremendous growth by bringing together some of the best and most successful financial technology companies in the world.",
      "Over 2,000 of the world’s leading corporations, including 50% of the Fortune 500 and 30% of the world’s central banks, trust ION solutions to manage their cash, in-house banking, commodity supply chain, trading and risk.",
      "Over 800 of the world’s leading banks and broker-dealers use our electronic trading platforms to operate the world’s financial market infrastructure.",
    ],
    status: "applied",
  },
  {
    id: "8",
    jobTitle: "System Administrator",
    companyName: "SysAdmin Solutions",
    jobPackage: "12 - 17 LPA",
    workType: "Remote",
    experience: "5 - 7 years",
    location: "Kolkata",
    roleType: "Fulltime",
    skills: ["Linux", "Windows Server", "Networking", "Shell Scripting"],
    applyLink: "https://example.com/apply",
    jobDescription:
      "As a Software Engineer you will be specializing in Java and SQL and play a vital role in designing, developing, and maintaining robust software applications that leverage the strengths of Java for application logic and SQL for database interactions. This role requires a solid understanding of Java programming, including object-oriented design principles as well as writing efficient SQL queries in relational databases or NoSQL. This role also involves debugging and resolving software defects, optimizing code for performance, and maintain code quality.",
    keyResponsibilities: [
      "Analyze, design, develop, test, and maintain scalable applications using Java for backend and modern JavaScript frameworks for frontend",
      "Build distributed system based on service-oriented architecture and SOLID design principles",
      "Develop and optimize SQL queries, and database schema designs",
      "Write clean, maintainable, and efficient code following best practices and coding standards",
      "Be passionate about delivering quality code and build culture of continuous learning and improvement in team by identifying technical debts/improvements",
      "Have the desire to collaborate, and like sharing and learning from your colleagues",
      "Provide input and guidance to resolve issues and meet objectives",
    ],
    requiredSkillsExperienceQualifications: [
      "BE/BTech or MS degree in Computer Science from a reputed university",
      "4+ years of full-stack, hands on experience designing & developing of product development experience in Java and related technologies",
      "Experience implementing Design Patterns/SOLID principles/OOPS",
      "Experience developing and working with databases (Oracle, MSSQL, NoSQL)",
      "Experience in successful implementation/adoption of Agile and Scrum methodologies",
      "Test-driven development, which includes Unit and End-to-End Testing",
      "Excellent analytical, problem-solving and communication skills",
      "Experience working with teams across different time-zones and countries",
      "Ability to work independently and collaboratively",
    ],
    aboutCompany: [
      "We’re a diverse group of visionary innovators who provide trading and workflow automation software, high-value analytics, and strategic consulting to corporations, central banks, financial institutions, and governments. Founded in 1999, we’ve achieved tremendous growth by bringing together some of the best and most successful financial technology companies in the world.",
      "Over 2,000 of the world’s leading corporations, including 50% of the Fortune 500 and 30% of the world’s central banks, trust ION solutions to manage their cash, in-house banking, commodity supply chain, trading and risk.",
      "Over 800 of the world’s leading banks and broker-dealers use our electronic trading platforms to operate the world’s financial market infrastructure.",
    ],
    status: "interviewing",
  },
  {
    id: "9",
    jobTitle: "QA Engineer",
    companyName: "QualityFirst",
    jobPackage: "9 - 14 LPA",
    workType: "Onsite",
    experience: "2 - 4 years",
    location: "Ahmedabad",
    roleType: "Contract",
    skills: ["Selenium", "Jenkins", "Test Automation", "Manual Testing"],
    applyLink: "https://example.com/apply",
    jobDescription:
      "As a Software Engineer you will be specializing in Java and SQL and play a vital role in designing, developing, and maintaining robust software applications that leverage the strengths of Java for application logic and SQL for database interactions. This role requires a solid understanding of Java programming, including object-oriented design principles as well as writing efficient SQL queries in relational databases or NoSQL. This role also involves debugging and resolving software defects, optimizing code for performance, and maintain code quality.",
    keyResponsibilities: [
      "Analyze, design, develop, test, and maintain scalable applications using Java for backend and modern JavaScript frameworks for frontend",
      "Build distributed system based on service-oriented architecture and SOLID design principles",
      "Develop and optimize SQL queries, and database schema designs",
      "Write clean, maintainable, and efficient code following best practices and coding standards",
      "Be passionate about delivering quality code and build culture of continuous learning and improvement in team by identifying technical debts/improvements",
      "Have the desire to collaborate, and like sharing and learning from your colleagues",
      "Provide input and guidance to resolve issues and meet objectives",
    ],
    requiredSkillsExperienceQualifications: [
      "BE/BTech or MS degree in Computer Science from a reputed university",
      "4+ years of full-stack, hands on experience designing & developing of product development experience in Java and related technologies",
      "Experience implementing Design Patterns/SOLID principles/OOPS",
      "Experience developing and working with databases (Oracle, MSSQL, NoSQL)",
      "Experience in successful implementation/adoption of Agile and Scrum methodologies",
      "Test-driven development, which includes Unit and End-to-End Testing",
      "Excellent analytical, problem-solving and communication skills",
      "Experience working with teams across different time-zones and countries",
      "Ability to work independently and collaboratively",
    ],
    aboutCompany: [
      "We’re a diverse group of visionary innovators who provide trading and workflow automation software, high-value analytics, and strategic consulting to corporations, central banks, financial institutions, and governments. Founded in 1999, we’ve achieved tremendous growth by bringing together some of the best and most successful financial technology companies in the world.",
      "Over 2,000 of the world’s leading corporations, including 50% of the Fortune 500 and 30% of the world’s central banks, trust ION solutions to manage their cash, in-house banking, commodity supply chain, trading and risk.",
      "Over 800 of the world’s leading banks and broker-dealers use our electronic trading platforms to operate the world’s financial market infrastructure.",
    ],
    status: "noReply",
  },
  {
    id: "10",
    jobTitle: "Cloud Architect",
    companyName: "CloudMasters",
    jobPackage: "18 - 25 LPA",
    workType: "Hybrid",
    experience: "6 - 8 years",
    location: "Gurgaon, India",
    roleType: "Fulltime",
    skills: ["AWS", "Azure", "GCP", "Cloud Security"],
    applyLink: "https://example.com/apply",
    jobDescription:
      "As a Software Engineer you will be specializing in Java and SQL and play a vital role in designing, developing, and maintaining robust software applications that leverage the strengths of Java for application logic and SQL for database interactions. This role requires a solid understanding of Java programming, including object-oriented design principles as well as writing efficient SQL queries in relational databases or NoSQL. This role also involves debugging and resolving software defects, optimizing code for performance, and maintain code quality.",
    keyResponsibilities: [
      "Analyze, design, develop, test, and maintain scalable applications using Java for backend and modern JavaScript frameworks for frontend",
      "Build distributed system based on service-oriented architecture and SOLID design principles",
      "Develop and optimize SQL queries, and database schema designs",
      "Write clean, maintainable, and efficient code following best practices and coding standards",
      "Be passionate about delivering quality code and build culture of continuous learning and improvement in team by identifying technical debts/improvements",
      "Have the desire to collaborate, and like sharing and learning from your colleagues",
      "Provide input and guidance to resolve issues and meet objectives",
    ],
    requiredSkillsExperienceQualifications: [
      "BE/BTech or MS degree in Computer Science from a reputed university",
      "4+ years of full-stack, hands on experience designing & developing of product development experience in Java and related technologies",
      "Experience implementing Design Patterns/SOLID principles/OOPS",
      "Experience developing and working with databases (Oracle, MSSQL, NoSQL)",
      "Experience in successful implementation/adoption of Agile and Scrum methodologies",
      "Test-driven development, which includes Unit and End-to-End Testing",
      "Excellent analytical, problem-solving and communication skills",
      "Experience working with teams across different time-zones and countries",
      "Ability to work independently and collaboratively",
    ],
    aboutCompany: [
      "We’re a diverse group of visionary innovators who provide trading and workflow automation software, high-value analytics, and strategic consulting to corporations, central banks, financial institutions, and governments. Founded in 1999, we’ve achieved tremendous growth by bringing together some of the best and most successful financial technology companies in the world.",
      "Over 2,000 of the world’s leading corporations, including 50% of the Fortune 500 and 30% of the world’s central banks, trust ION solutions to manage their cash, in-house banking, commodity supply chain, trading and risk.",
      "Over 800 of the world’s leading banks and broker-dealers use our electronic trading platforms to operate the world’s financial market infrastructure.",
    ],
    status: "archieved",
  },
  {
    id: "11",
    jobTitle: "UI/UX Designer",
    companyName: "DesignHub",
    jobPackage: "10 - 15 LPA",
    workType: "Hybrid",
    experience: "3 - 5 years",
    location: "Noida, India",
    roleType: "Fulltime",
    skills: ["Sketch", "Figma", "Adobe XD", "User Research"],
    applyLink: "https://example.com/apply",
    jobDescription:
      "As a Software Engineer you will be specializing in Java and SQL and play a vital role in designing, developing, and maintaining robust software applications that leverage the strengths of Java for application logic and SQL for database interactions. This role requires a solid understanding of Java programming, including object-oriented design principles as well as writing efficient SQL queries in relational databases or NoSQL. This role also involves debugging and resolving software defects, optimizing code for performance, and maintain code quality.",
    keyResponsibilities: [
      "Analyze, design, develop, test, and maintain scalable applications using Java for backend and modern JavaScript frameworks for frontend",
      "Build distributed system based on service-oriented architecture and SOLID design principles",
      "Develop and optimize SQL queries, and database schema designs",
      "Write clean, maintainable, and efficient code following best practices and coding standards",
      "Be passionate about delivering quality code and build culture of continuous learning and improvement in team by identifying technical debts/improvements",
      "Have the desire to collaborate, and like sharing and learning from your colleagues",
      "Provide input and guidance to resolve issues and meet objectives",
    ],
    requiredSkillsExperienceQualifications: [
      "BE/BTech or MS degree in Computer Science from a reputed university",
      "4+ years of full-stack, hands on experience designing & developing of product development experience in Java and related technologies",
      "Experience implementing Design Patterns/SOLID principles/OOPS",
      "Experience developing and working with databases (Oracle, MSSQL, NoSQL)",
      "Experience in successful implementation/adoption of Agile and Scrum methodologies",
      "Test-driven development, which includes Unit and End-to-End Testing",
      "Excellent analytical, problem-solving and communication skills",
      "Experience working with teams across different time-zones and countries",
      "Ability to work independently and collaboratively",
    ],
    aboutCompany: [
      "We’re a diverse group of visionary innovators who provide trading and workflow automation software, high-value analytics, and strategic consulting to corporations, central banks, financial institutions, and governments. Founded in 1999, we’ve achieved tremendous growth by bringing together some of the best and most successful financial technology companies in the world.",
      "Over 2,000 of the world’s leading corporations, including 50% of the Fortune 500 and 30% of the world’s central banks, trust ION solutions to manage their cash, in-house banking, commodity supply chain, trading and risk.",
      "Over 800 of the world’s leading banks and broker-dealers use our electronic trading platforms to operate the world’s financial market infrastructure.",
    ],
    status: "followUpRequired",
  },

  {
    id: "12",
    jobTitle: "UI/UX Designer",
    companyName: "DesignHub",
    jobPackage: "10 - 15 LPA",
    workType: "Hybrid",
    experience: "3 - 5 years",
    location: "Chennai",
    roleType: "Fulltime",
    skills: ["Sketch", "Figma", "Adobe XD", "User Research"],
    applyLink: "https://example.com/apply",
    jobDescription:
      "As a Software Engineer you will be specializing in Java and SQL and play a vital role in designing, developing, and maintaining robust software applications that leverage the strengths of Java for application logic and SQL for database interactions. This role requires a solid understanding of Java programming, including object-oriented design principles as well as writing efficient SQL queries in relational databases or NoSQL. This role also involves debugging and resolving software defects, optimizing code for performance, and maintain code quality.",
    keyResponsibilities: [
      "Analyze, design, develop, test, and maintain scalable applications using Java for backend and modern JavaScript frameworks for frontend",
      "Build distributed system based on service-oriented architecture and SOLID design principles",
      "Develop and optimize SQL queries, and database schema designs",
      "Write clean, maintainable, and efficient code following best practices and coding standards",
      "Be passionate about delivering quality code and build culture of continuous learning and improvement in team by identifying technical debts/improvements",
      "Have the desire to collaborate, and like sharing and learning from your colleagues",
      "Provide input and guidance to resolve issues and meet objectives",
    ],
    requiredSkillsExperienceQualifications: [
      "BE/BTech or MS degree in Computer Science from a reputed university",
      "4+ years of full-stack, hands on experience designing & developing of product development experience in Java and related technologies",
      "Experience implementing Design Patterns/SOLID principles/OOPS",
      "Experience developing and working with databases (Oracle, MSSQL, NoSQL)",
      "Experience in successful implementation/adoption of Agile and Scrum methodologies",
      "Test-driven development, which includes Unit and End-to-End Testing",
      "Excellent analytical, problem-solving and communication skills",
      "Experience working with teams across different time-zones and countries",
      "Ability to work independently and collaboratively",
    ],
    aboutCompany: [
      "We’re a diverse group of visionary innovators who provide trading and workflow automation software, high-value analytics, and strategic consulting to corporations, central banks, financial institutions, and governments. Founded in 1999, we’ve achieved tremendous growth by bringing together some of the best and most successful financial technology companies in the world.",
      "Over 2,000 of the world’s leading corporations, including 50% of the Fortune 500 and 30% of the world’s central banks, trust ION solutions to manage their cash, in-house banking, commodity supply chain, trading and risk.",
      "Over 800 of the world’s leading banks and broker-dealers use our electronic trading platforms to operate the world’s financial market infrastructure.",
    ],
    status: "noReply",
  },

  {
    id: "13",
    jobTitle: "UI/UX Designer",
    companyName: "DesignHub",
    jobPackage: "10 - 15 LPA",
    workType: "Hybrid",
    experience: "3 - 5 years",
    location: "Delhi",
    roleType: "Fulltime",
    skills: ["Sketch", "Figma", "Adobe XD", "User Research"],
    applyLink: "https://example.com/apply",
    jobDescription:
      "As a Software Engineer you will be specializing in Java and SQL and play a vital role in designing, developing, and maintaining robust software applications that leverage the strengths of Java for application logic and SQL for database interactions. This role requires a solid understanding of Java programming, including object-oriented design principles as well as writing efficient SQL queries in relational databases or NoSQL. This role also involves debugging and resolving software defects, optimizing code for performance, and maintain code quality.",
    keyResponsibilities: [
      "Analyze, design, develop, test, and maintain scalable applications using Java for backend and modern JavaScript frameworks for frontend",
      "Build distributed system based on service-oriented architecture and SOLID design principles",
      "Develop and optimize SQL queries, and database schema designs",
      "Write clean, maintainable, and efficient code following best practices and coding standards",
      "Be passionate about delivering quality code and build culture of continuous learning and improvement in team by identifying technical debts/improvements",
      "Have the desire to collaborate, and like sharing and learning from your colleagues",
      "Provide input and guidance to resolve issues and meet objectives",
    ],
    requiredSkillsExperienceQualifications: [
      "BE/BTech or MS degree in Computer Science from a reputed university",
      "4+ years of full-stack, hands on experience designing & developing of product development experience in Java and related technologies",
      "Experience implementing Design Patterns/SOLID principles/OOPS",
      "Experience developing and working with databases (Oracle, MSSQL, NoSQL)",
      "Experience in successful implementation/adoption of Agile and Scrum methodologies",
      "Test-driven development, which includes Unit and End-to-End Testing",
      "Excellent analytical, problem-solving and communication skills",
      "Experience working with teams across different time-zones and countries",
      "Ability to work independently and collaboratively",
    ],
    aboutCompany: [
      "We’re a diverse group of visionary innovators who provide trading and workflow automation software, high-value analytics, and strategic consulting to corporations, central banks, financial institutions, and governments. Founded in 1999, we’ve achieved tremendous growth by bringing together some of the best and most successful financial technology companies in the world.",
      "Over 2,000 of the world’s leading corporations, including 50% of the Fortune 500 and 30% of the world’s central banks, trust ION solutions to manage their cash, in-house banking, commodity supply chain, trading and risk.",
      "Over 800 of the world’s leading banks and broker-dealers use our electronic trading platforms to operate the world’s financial market infrastructure.",
    ],
    status: "followUpRequired",
  },
];

export const testimonials = [
  {
    image: "/static/images/testimonialsabya2.png",
    comment:
      "“AiPply.io made my job search effortless! The automated matches and tracking saved me hours, and I never missed an opportunity. Highly recommend!”",
    name: "Sabya Sachi Mishra",
    position: "Data Scientist, BEACON Consulting",
    stars: 5,
    link: "https://www.linkedin.com/in/ssm93"
  },
  {
    image: "/static/images/testimonialkartikeya2.png",
    comment:
      "“AiPply.io took away my stress and manual effort. The tool is trustworthy and gives actual trackable results.”",
    name: "Kartikeya Madnani",
    position: "Sales Development Representative, CultureX",
    stars: 5,
    link: "https://www.linkedin.com/in/kartikeya8"
  },
  {
    image: "/static/images/testimonialkunal2.png",
    comment:
      "“Not only I landed a great company, but also in my choice of location and range. Thanks a ton!”",
    name: "Kunal Gupta",
    position: "Sales Manager, InfoEdge",
    stars: 5,
    link: "https://www.linkedin.com/in/kunalg26"
  },
];

export const getWorkTypeImage = (workType: string) => {
  switch (workType) {
    case "Onsite":
      return "/static/icons/Dot.svg";
    case "Hybrid":
      return "/static/icons/pinkDot.svg";
    case "Remote":
      return "/static/icons/blueDot.svg";
    default:
      return "/static/icons/Dot.svg";
  }
};

export const getJobDataByLocation = () => {
  const locationData = jobBoardData.reduce((acc: { [key: string]: number }, job) => {
    if (!acc[job.location]) {
      acc[job.location] = 0;
    }
    acc[job.location]++;
    return acc;
  }, {});

  return Object.keys(locationData).map((location) => ({
    location,
    count: locationData[location],
  }));
};

export const DashboardData = [
  {
    id: "1",
    title: "Job Searches",
    totalNumber: 27,
  },
  {
    id: "2",
    title: "Total matches",
    totalNumber: 21,
  },
  {
    id: "3",
    title: "Total applied",
    totalNumber: 18,
  },
  {
    id: "4",
    title: "Emails sent",
    totalNumber: 16,
  },
  {
    id: "5",
    title: "Callbacks",
    totalNumber: 10,
  },
  {
    id: "6",
    title: "Interview scheduled",
    totalNumber: 7,
  },
  {
    id: "7",
    title: "Pending",
    totalNumber: 3,
  },
  {
    id: "8",
    title: "Offers",
    totalNumber: 4,
  },
];

export const getReminderCardsByStatus = (status: string) => {
  return jobBoardData.filter(job => job.status === status).map(job => ({
    id: job.id,
    jobTitle: job.jobTitle,
    companyName: job.companyName,
    location: job.location,
    status: job.status,
  }));
};

export const salaryRanges = [
  { label: "As per Industry Standards", range: [0, Infinity] },
  { label: "0-3 LPA", range: [0, 300000] },
  { label: "3-6 LPA", range: [300001, 600000] },
  { label: "6-9 LPA", range: [600001, 900000] },
  { label: "9-12 LPA", range: [900001, 1200000] },
  { label: "12-15 LPA", range: [1200001, 1500000] },
  { label: "15-20 LPA", range: [1500001, 2000000] },
  { label: "20+ LPA", range: [2000001, Infinity] },
];

export const experienceOptions = [
  { label: "0 - 3 Years", range: [0, 3] },
  { label: "3 - 6 Years", range: [3, 6] },
  { label: "6 - 9 Years", range: [6, 9] },
  { label: "9 - 15 Years", range: [9, 15] },
];

export const jobTypes = [
  { label: "Full-time", value: "full-time" },
  { label: "Part-time", value: "part-time" },
  { label: "Internship", value: "internship" },
];



export const features = [
  {
    name: "Custom Job Listings",
    redirectUrl: "/features/job-listings",
  },
  {
    name: "Auto Job Application",
    redirectUrl: "/features/auto-apply",
  },
  { name: "Job Tracker", redirectUrl: "/features/job-tracker" },
  { name: "AIMock Interview", redirectUrl: "/ai-mockinterview" },
];

